# 本地配置 (使用时去除文件 “-tmp”后缀)

spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rich_code_weaver
    username: root
    password: 12345
  # redis
  data:
    redis:
      database: 5
      port: 6379
      host: localhost
      password:
      # 连接超时时间
      timeout: 5000
  # JavaMailSender 邮件服务配置（用于注册邮箱验证码）
  mail:
    host: smtp.qq.com
    username: xxxxxx
    password: xxxxxx
    port: 465
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

# 邮件验证码配置
email-code:
  # 发件人显示名称和邮箱
  from: "RichCodeWeaver <xxxxxx@xxxxxx.com>"

# MyBatis Flex 配置
mybatis-flex:
  # 打印 SQL 语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Dubbo
dubbo:
  registry:
    # nacos 注册中心启动地址
    address: nacos://xxxxxx:8848?username=nacos&password=nacos
    register-mode: interface
  protocol:
    name: tri
    port: 50052
  consumer:
    timeout: 60000
  provider:
    timeout: 60000
  # Dubbo QoS 配置
  application:
    qos-port: 33334

# Spring Boot Admin Client 配置
spring.boot.admin.client:
  # Spring Boot Admin Server 地址
  url: http://localhost:9001
  instance:
    # 服务实例名称
    name: ${spring.application.name}
    # 服务访问地址
    service-base-url: http://localhost:${server.port}

# 阿里云 OSS 配置（用于文件上传，请填写实际值）
aliyun:
  oss:
    end-point: xxxxxx
    access-key-id: xxxxxx
    access-key-secret: xxxxxx
    bucket-name: xxxxxx